### ISSUE TITLE
evetry time i tey to open the exe the command opens shows text then rips onley on 2.1.0

### ISSUE THREAD

**Issue by twitchplayskh** [howroyd/simonsays#71]
i have python and all that but when i go to open the bot v 2.1.0 it shows cmd then rip this is just happening in 2.1.0

**Comment by AshKapow** [comment]
I have the same issue, this is the output:

`Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\simonsays_drgreengiant\simonsays.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\simonsays_drgreengiant\config.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\simonsays_drgreengiant\twitchactions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\simonsays_drgreengiant\phasmoactions\phasmoactions.py", line 7, in <module>
ImportError: cannot import name 'errorcodes' from 'src.simonsays_drgreengiant.phasmoactions' (unknown location)
[20432] Failed to execute script 'main' due to unhandled exception!`
